server:
  port: 8089
eureka:
  instance:
    hostname: eureka2
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://lihy:520@eureka1:8088/eureka/,http://lihy:520@eureka3:8090/eureka/