server:
  port: 8081
spring:
  application:
    name: view-user-service
    # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # autoReconnect=true自动重连(mysql5以上无效)，allowMultiQueries=true支持批量更新
    url: jdbc:mysql://localhost:3306/view?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password:
# mybatis mapper xml 配置
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://lihy:520@localhost:8088/eureka/