server:
  port: 8888
spring:
  application:
    name: view-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huanyingtoyou/view-home-config
          search-paths: repository
          username: huanyingtoyou
          password: 13526283875wyzd
eureka:
  client:
    serviceUrl:
      defaultZone: http://lihy:520@localhost:8088/eureka/
management:
  security:
    enabled: false
security:
  basic:
    enabled: true #开启基于http basic的认证
  user:
    name: lihy
    password: 123456